spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: git@github.com:moranlanshan/study.git
          username: moranlanshan
          password: wxwwt123
  rabbitmq:
    port: 5672
    username: admin
    password: admin
    host: 47.107.229.169
    connection-timeout: 3000
    virtual-host: my_vhost


eureka:
  client:
    service-url:
      defualtZone:  http://localhost:8761/eureka/
server:
  port: 8086
management:
  endpoints:
    web:
      exposure:
        include: "*"




